// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::actor_kind_type::ActorKind;
use super::actor_type::Actor;
use super::db_vec_3_type::DbVec3;
use super::move_intent_type::MoveIntent;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `actor`.
///
/// Obtain a handle from the [`ActorTableAccess::actor`] method on [`super::RemoteTables`],
/// like `ctx.db.actor()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.actor().on_insert(...)`.
pub struct ActorTableHandle<'ctx> {
    imp: __sdk::TableHandle<Actor>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `actor`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ActorTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ActorTableHandle`], which mediates access to the table `actor`.
    fn actor(&self) -> ActorTableHandle<'_>;
}

impl ActorTableAccess for super::RemoteTables {
    fn actor(&self) -> ActorTableHandle<'_> {
        ActorTableHandle {
            imp: self.imp.get_table::<Actor>("actor"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ActorInsertCallbackId(__sdk::CallbackId);
pub struct ActorDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ActorTableHandle<'ctx> {
    type Row = Actor;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Actor> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ActorInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ActorInsertCallbackId {
        ActorInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ActorInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ActorDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ActorDeleteCallbackId {
        ActorDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ActorDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Actor>("actor");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct ActorUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ActorTableHandle<'ctx> {
    type UpdateCallbackId = ActorUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ActorUpdateCallbackId {
        ActorUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ActorUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Actor>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Actor>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `actor`,
/// which allows point queries on the field of the same name
/// via the [`ActorIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.actor().id().find(...)`.
pub struct ActorIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Actor, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ActorTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `actor`.
    pub fn id(&self) -> ActorIdUnique<'ctx> {
        ActorIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ActorIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Actor> {
        self.imp.find(col_val)
    }
}
