// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::actor_kind_type::ActorKind;
use super::db_quat_type::DbQuat;
use super::db_vec_3_type::DbVec3;
use super::move_intent_type::MoveIntent;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Actor {
    pub id: u64,
    pub kind: ActorKind,
    pub translation: DbVec3,
    pub rotation: DbQuat,
    pub scale: DbVec3,
    pub move_intent: MoveIntent,
}

impl __sdk::InModule for Actor {
    type Module = super::RemoteModule;
}
