// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::actor_in_aoi_type::ActorInAoi;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `actor_in_aoi`.
///
/// Obtain a handle from the [`ActorInAoiTableAccess::actor_in_aoi`] method on [`super::RemoteTables`],
/// like `ctx.db.actor_in_aoi()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.actor_in_aoi().on_insert(...)`.
pub struct ActorInAoiTableHandle<'ctx> {
    imp: __sdk::TableHandle<ActorInAoi>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `actor_in_aoi`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ActorInAoiTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ActorInAoiTableHandle`], which mediates access to the table `actor_in_aoi`.
    fn actor_in_aoi(&self) -> ActorInAoiTableHandle<'_>;
}

impl ActorInAoiTableAccess for super::RemoteTables {
    fn actor_in_aoi(&self) -> ActorInAoiTableHandle<'_> {
        ActorInAoiTableHandle {
            imp: self.imp.get_table::<ActorInAoi>("actor_in_aoi"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ActorInAoiInsertCallbackId(__sdk::CallbackId);
pub struct ActorInAoiDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ActorInAoiTableHandle<'ctx> {
    type Row = ActorInAoi;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ActorInAoi> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ActorInAoiInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ActorInAoiInsertCallbackId {
        ActorInAoiInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ActorInAoiInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ActorInAoiDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ActorInAoiDeleteCallbackId {
        ActorInAoiDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ActorInAoiDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ActorInAoi>("actor_in_aoi");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct ActorInAoiUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ActorInAoiTableHandle<'ctx> {
    type UpdateCallbackId = ActorInAoiUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ActorInAoiUpdateCallbackId {
        ActorInAoiUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ActorInAoiUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ActorInAoi>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ActorInAoi>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `actor_in_aoi`,
/// which allows point queries on the field of the same name
/// via the [`ActorInAoiIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.actor_in_aoi().id().find(...)`.
pub struct ActorInAoiIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ActorInAoi, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ActorInAoiTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `actor_in_aoi`.
    pub fn id(&self) -> ActorInAoiIdUnique<'ctx> {
        ActorInAoiIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ActorInAoiIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ActorInAoi> {
        self.imp.find(col_val)
    }
}
