// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::aoi_tick_timer_type::AoiTickTimer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `aoi_tick_timer`.
///
/// Obtain a handle from the [`AoiTickTimerTableAccess::aoi_tick_timer`] method on [`super::RemoteTables`],
/// like `ctx.db.aoi_tick_timer()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.aoi_tick_timer().on_insert(...)`.
pub struct AoiTickTimerTableHandle<'ctx> {
    imp: __sdk::TableHandle<AoiTickTimer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `aoi_tick_timer`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AoiTickTimerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AoiTickTimerTableHandle`], which mediates access to the table `aoi_tick_timer`.
    fn aoi_tick_timer(&self) -> AoiTickTimerTableHandle<'_>;
}

impl AoiTickTimerTableAccess for super::RemoteTables {
    fn aoi_tick_timer(&self) -> AoiTickTimerTableHandle<'_> {
        AoiTickTimerTableHandle {
            imp: self.imp.get_table::<AoiTickTimer>("aoi_tick_timer"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AoiTickTimerInsertCallbackId(__sdk::CallbackId);
pub struct AoiTickTimerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for AoiTickTimerTableHandle<'ctx> {
    type Row = AoiTickTimer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AoiTickTimer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AoiTickTimerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AoiTickTimerInsertCallbackId {
        AoiTickTimerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AoiTickTimerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AoiTickTimerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AoiTickTimerDeleteCallbackId {
        AoiTickTimerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AoiTickTimerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<AoiTickTimer>("aoi_tick_timer");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}
pub struct AoiTickTimerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AoiTickTimerTableHandle<'ctx> {
    type UpdateCallbackId = AoiTickTimerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AoiTickTimerUpdateCallbackId {
        AoiTickTimerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AoiTickTimerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<AoiTickTimer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AoiTickTimer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `scheduled_id` unique index on the table `aoi_tick_timer`,
/// which allows point queries on the field of the same name
/// via the [`AoiTickTimerScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.aoi_tick_timer().scheduled_id().find(...)`.
pub struct AoiTickTimerScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<AoiTickTimer, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AoiTickTimerTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `aoi_tick_timer`.
    pub fn scheduled_id(&self) -> AoiTickTimerScheduledIdUnique<'ctx> {
        AoiTickTimerScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AoiTickTimerScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<AoiTickTimer> {
        self.imp.find(col_val)
    }
}
