// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::aoi_tick_timer_type::AoiTickTimer;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AoiTickReducerArgs {
    pub aoi_tick_timer: AoiTickTimer,
}

impl From<AoiTickReducerArgs> for super::Reducer {
    fn from(args: AoiTickReducerArgs) -> Self {
        Self::AoiTickReducer {
            aoi_tick_timer: args.aoi_tick_timer,
        }
    }
}

impl __sdk::InModule for AoiTickReducerArgs {
    type Module = super::RemoteModule;
}

pub struct AoiTickReducerCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `aoi_tick_reducer`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait aoi_tick_reducer {
    /// Request that the remote module invoke the reducer `aoi_tick_reducer` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_aoi_tick_reducer`] callbacks.
    fn aoi_tick_reducer(&self, aoi_tick_timer: AoiTickTimer) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `aoi_tick_reducer`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AoiTickReducerCallbackId`] can be passed to [`Self::remove_on_aoi_tick_reducer`]
    /// to cancel the callback.
    fn on_aoi_tick_reducer(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &AoiTickTimer) + Send + 'static,
    ) -> AoiTickReducerCallbackId;
    /// Cancel a callback previously registered by [`Self::on_aoi_tick_reducer`],
    /// causing it not to run in the future.
    fn remove_on_aoi_tick_reducer(&self, callback: AoiTickReducerCallbackId);
}

impl aoi_tick_reducer for super::RemoteReducers {
    fn aoi_tick_reducer(&self, aoi_tick_timer: AoiTickTimer) -> __sdk::Result<()> {
        self.imp
            .call_reducer("aoi_tick_reducer", AoiTickReducerArgs { aoi_tick_timer })
    }
    fn on_aoi_tick_reducer(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &AoiTickTimer) + Send + 'static,
    ) -> AoiTickReducerCallbackId {
        AoiTickReducerCallbackId(self.imp.on_reducer(
            "aoi_tick_reducer",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::AoiTickReducer { aoi_tick_timer },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, aoi_tick_timer)
            }),
        ))
    }
    fn remove_on_aoi_tick_reducer(&self, callback: AoiTickReducerCallbackId) {
        self.imp.remove_on_reducer("aoi_tick_reducer", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `aoi_tick_reducer`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_aoi_tick_reducer {
    /// Set the call-reducer flags for the reducer `aoi_tick_reducer` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn aoi_tick_reducer(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_aoi_tick_reducer for super::SetReducerFlags {
    fn aoi_tick_reducer(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("aoi_tick_reducer", flags);
    }
}
