// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::db_capsule_type::DbCapsule;
use super::db_cone_type::DbCone;
use super::db_cylinder_type::DbCylinder;
use super::db_round_cone_type::DbRoundCone;
use super::db_round_cuboid_type::DbRoundCuboid;
use super::db_round_cylinder_type::DbRoundCylinder;
use super::db_vec_3_type::DbVec3;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub enum ColliderShape {
    Plane(f32),

    Cuboid(DbVec3),

    Sphere(f32),

    Capsule(DbCapsule),

    Cylinder(DbCylinder),

    Cone(DbCone),

    RoundCuboid(DbRoundCuboid),

    RoundCylinder(DbRoundCylinder),

    RoundCone(DbRoundCone),
}

impl __sdk::InModule for ColliderShape {
    type Module = super::RemoteModule;
}
