// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EnterWorldArgs {}

impl From<EnterWorldArgs> for super::Reducer {
    fn from(args: EnterWorldArgs) -> Self {
        Self::EnterWorld
    }
}

impl __sdk::InModule for EnterWorldArgs {
    type Module = super::RemoteModule;
}

pub struct EnterWorldCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `enter_world`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait enter_world {
    /// Request that the remote module invoke the reducer `enter_world` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_enter_world`] callbacks.
    fn enter_world(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `enter_world`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`EnterWorldCallbackId`] can be passed to [`Self::remove_on_enter_world`]
    /// to cancel the callback.
    fn on_enter_world(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> EnterWorldCallbackId;
    /// Cancel a callback previously registered by [`Self::on_enter_world`],
    /// causing it not to run in the future.
    fn remove_on_enter_world(&self, callback: EnterWorldCallbackId);
}

impl enter_world for super::RemoteReducers {
    fn enter_world(&self) -> __sdk::Result<()> {
        self.imp.call_reducer("enter_world", EnterWorldArgs {})
    }
    fn on_enter_world(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> EnterWorldCallbackId {
        EnterWorldCallbackId(self.imp.on_reducer(
            "enter_world",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::EnterWorld {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_enter_world(&self, callback: EnterWorldCallbackId) {
        self.imp.remove_on_reducer("enter_world", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `enter_world`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_enter_world {
    /// Set the call-reducer flags for the reducer `enter_world` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn enter_world(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_enter_world for super::SetReducerFlags {
    fn enter_world(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("enter_world", flags);
    }
}
