// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct KccSettings {
    pub id: u32,
    pub offset: f32,
    pub max_slope_climb_deg: f32,
    pub min_slope_slide_deg: f32,
    pub autostep_max_height: f32,
    pub autostep_min_width: f32,
    pub slide: bool,
    pub normal_nudge_factor: f32,
    pub fall_speed_mps: f32,
    pub grounded_down_bias_mps: f32,
    pub hard_airborne_probe_distance: f32,
    pub point_acceptance_radius_sq: f32,
}

impl __sdk::InModule for KccSettings {
    type Module = super::RemoteModule;
}
