// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::kcc_settings_type::KccSettings;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `kcc_settings`.
///
/// Obtain a handle from the [`KccSettingsTableAccess::kcc_settings`] method on [`super::RemoteTables`],
/// like `ctx.db.kcc_settings()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.kcc_settings().on_insert(...)`.
pub struct KccSettingsTableHandle<'ctx> {
    imp: __sdk::TableHandle<KccSettings>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `kcc_settings`.
///
/// Implemented for [`super::RemoteTables`].
pub trait KccSettingsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`KccSettingsTableHandle`], which mediates access to the table `kcc_settings`.
    fn kcc_settings(&self) -> KccSettingsTableHandle<'_>;
}

impl KccSettingsTableAccess for super::RemoteTables {
    fn kcc_settings(&self) -> KccSettingsTableHandle<'_> {
        KccSettingsTableHandle {
            imp: self.imp.get_table::<KccSettings>("kcc_settings"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct KccSettingsInsertCallbackId(__sdk::CallbackId);
pub struct KccSettingsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for KccSettingsTableHandle<'ctx> {
    type Row = KccSettings;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = KccSettings> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = KccSettingsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> KccSettingsInsertCallbackId {
        KccSettingsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: KccSettingsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = KccSettingsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> KccSettingsDeleteCallbackId {
        KccSettingsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: KccSettingsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<KccSettings>("kcc_settings");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}
pub struct KccSettingsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for KccSettingsTableHandle<'ctx> {
    type UpdateCallbackId = KccSettingsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> KccSettingsUpdateCallbackId {
        KccSettingsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: KccSettingsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<KccSettings>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<KccSettings>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `kcc_settings`,
/// which allows point queries on the field of the same name
/// via the [`KccSettingsIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.kcc_settings().id().find(...)`.
pub struct KccSettingsIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<KccSettings, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> KccSettingsTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `kcc_settings`.
    pub fn id(&self) -> KccSettingsIdUnique<'ctx> {
        KccSettingsIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> KccSettingsIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<KccSettings> {
        self.imp.find(col_val)
    }
}
