// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct LeaveWorldArgs {}

impl From<LeaveWorldArgs> for super::Reducer {
    fn from(args: LeaveWorldArgs) -> Self {
        Self::LeaveWorld
    }
}

impl __sdk::InModule for LeaveWorldArgs {
    type Module = super::RemoteModule;
}

pub struct LeaveWorldCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `leave_world`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait leave_world {
    /// Request that the remote module invoke the reducer `leave_world` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_leave_world`] callbacks.
    fn leave_world(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `leave_world`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`LeaveWorldCallbackId`] can be passed to [`Self::remove_on_leave_world`]
    /// to cancel the callback.
    fn on_leave_world(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> LeaveWorldCallbackId;
    /// Cancel a callback previously registered by [`Self::on_leave_world`],
    /// causing it not to run in the future.
    fn remove_on_leave_world(&self, callback: LeaveWorldCallbackId);
}

impl leave_world for super::RemoteReducers {
    fn leave_world(&self) -> __sdk::Result<()> {
        self.imp.call_reducer("leave_world", LeaveWorldArgs {})
    }
    fn on_leave_world(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> LeaveWorldCallbackId {
        LeaveWorldCallbackId(self.imp.on_reducer(
            "leave_world",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::LeaveWorld {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_leave_world(&self, callback: LeaveWorldCallbackId) {
        self.imp.remove_on_reducer("leave_world", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `leave_world`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_leave_world {
    /// Set the call-reducer flags for the reducer `leave_world` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn leave_world(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_leave_world for super::SetReducerFlags {
    fn leave_world(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("leave_world", flags);
    }
}
