// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::movement_tick_timer_type::MovementTickTimer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `movement_tick_timer`.
///
/// Obtain a handle from the [`MovementTickTimerTableAccess::movement_tick_timer`] method on [`super::RemoteTables`],
/// like `ctx.db.movement_tick_timer()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.movement_tick_timer().on_insert(...)`.
pub struct MovementTickTimerTableHandle<'ctx> {
    imp: __sdk::TableHandle<MovementTickTimer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `movement_tick_timer`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MovementTickTimerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MovementTickTimerTableHandle`], which mediates access to the table `movement_tick_timer`.
    fn movement_tick_timer(&self) -> MovementTickTimerTableHandle<'_>;
}

impl MovementTickTimerTableAccess for super::RemoteTables {
    fn movement_tick_timer(&self) -> MovementTickTimerTableHandle<'_> {
        MovementTickTimerTableHandle {
            imp: self
                .imp
                .get_table::<MovementTickTimer>("movement_tick_timer"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MovementTickTimerInsertCallbackId(__sdk::CallbackId);
pub struct MovementTickTimerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MovementTickTimerTableHandle<'ctx> {
    type Row = MovementTickTimer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MovementTickTimer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MovementTickTimerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MovementTickTimerInsertCallbackId {
        MovementTickTimerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MovementTickTimerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MovementTickTimerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MovementTickTimerDeleteCallbackId {
        MovementTickTimerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MovementTickTimerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MovementTickTimer>("movement_tick_timer");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}
pub struct MovementTickTimerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MovementTickTimerTableHandle<'ctx> {
    type UpdateCallbackId = MovementTickTimerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MovementTickTimerUpdateCallbackId {
        MovementTickTimerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MovementTickTimerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<MovementTickTimer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MovementTickTimer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `scheduled_id` unique index on the table `movement_tick_timer`,
/// which allows point queries on the field of the same name
/// via the [`MovementTickTimerScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.movement_tick_timer().scheduled_id().find(...)`.
pub struct MovementTickTimerScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MovementTickTimer, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MovementTickTimerTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `movement_tick_timer`.
    pub fn scheduled_id(&self) -> MovementTickTimerScheduledIdUnique<'ctx> {
        MovementTickTimerScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MovementTickTimerScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<MovementTickTimer> {
        self.imp.find(col_val)
    }
}
