// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::db_quat_type::DbQuat;
use super::db_vec_3_type::DbVec3;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Projectile {
    pub id: u64,
    pub source_actor_id: Option<u64>,
    pub target_actor_id: Option<u64>,
    pub translation: DbVec3,
    pub rotation: DbQuat,
    pub scale: DbVec3,
    pub speed: f32,
    pub capsule_radius: f32,
    pub capsule_half_height: f32,
}

impl __sdk::InModule for Projectile {
    type Module = super::RemoteModule;
}
