// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::db_quat_type::DbQuat;
use super::db_vec_3_type::DbVec3;
use super::projectile_type::Projectile;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `projectile`.
///
/// Obtain a handle from the [`ProjectileTableAccess::projectile`] method on [`super::RemoteTables`],
/// like `ctx.db.projectile()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.projectile().on_insert(...)`.
pub struct ProjectileTableHandle<'ctx> {
    imp: __sdk::TableHandle<Projectile>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `projectile`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ProjectileTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ProjectileTableHandle`], which mediates access to the table `projectile`.
    fn projectile(&self) -> ProjectileTableHandle<'_>;
}

impl ProjectileTableAccess for super::RemoteTables {
    fn projectile(&self) -> ProjectileTableHandle<'_> {
        ProjectileTableHandle {
            imp: self.imp.get_table::<Projectile>("projectile"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ProjectileInsertCallbackId(__sdk::CallbackId);
pub struct ProjectileDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ProjectileTableHandle<'ctx> {
    type Row = Projectile;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Projectile> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ProjectileInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ProjectileInsertCallbackId {
        ProjectileInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ProjectileInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ProjectileDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ProjectileDeleteCallbackId {
        ProjectileDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ProjectileDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Projectile>("projectile");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct ProjectileUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ProjectileTableHandle<'ctx> {
    type UpdateCallbackId = ProjectileUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ProjectileUpdateCallbackId {
        ProjectileUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ProjectileUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Projectile>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Projectile>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `projectile`,
/// which allows point queries on the field of the same name
/// via the [`ProjectileIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.projectile().id().find(...)`.
pub struct ProjectileIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Projectile, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ProjectileTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `projectile`.
    pub fn id(&self) -> ProjectileIdUnique<'ctx> {
        ProjectileIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ProjectileIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Projectile> {
        self.imp.find(col_val)
    }
}
