// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::move_intent_type::MoveIntent;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RequestMoveArgs {
    pub intent: MoveIntent,
}

impl From<RequestMoveArgs> for super::Reducer {
    fn from(args: RequestMoveArgs) -> Self {
        Self::RequestMove {
            intent: args.intent,
        }
    }
}

impl __sdk::InModule for RequestMoveArgs {
    type Module = super::RemoteModule;
}

pub struct RequestMoveCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `request_move`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait request_move {
    /// Request that the remote module invoke the reducer `request_move` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_request_move`] callbacks.
    fn request_move(&self, intent: MoveIntent) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `request_move`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`RequestMoveCallbackId`] can be passed to [`Self::remove_on_request_move`]
    /// to cancel the callback.
    fn on_request_move(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &MoveIntent) + Send + 'static,
    ) -> RequestMoveCallbackId;
    /// Cancel a callback previously registered by [`Self::on_request_move`],
    /// causing it not to run in the future.
    fn remove_on_request_move(&self, callback: RequestMoveCallbackId);
}

impl request_move for super::RemoteReducers {
    fn request_move(&self, intent: MoveIntent) -> __sdk::Result<()> {
        self.imp
            .call_reducer("request_move", RequestMoveArgs { intent })
    }
    fn on_request_move(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &MoveIntent) + Send + 'static,
    ) -> RequestMoveCallbackId {
        RequestMoveCallbackId(self.imp.on_reducer(
            "request_move",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::RequestMove { intent },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, intent)
            }),
        ))
    }
    fn remove_on_request_move(&self, callback: RequestMoveCallbackId) {
        self.imp.remove_on_reducer("request_move", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `request_move`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_request_move {
    /// Set the call-reducer flags for the reducer `request_move` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn request_move(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_request_move for super::SetReducerFlags {
    fn request_move(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("request_move", flags);
    }
}
