// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SpawnFakeRemotesArgs {
    pub count: u32,
}

impl From<SpawnFakeRemotesArgs> for super::Reducer {
    fn from(args: SpawnFakeRemotesArgs) -> Self {
        Self::SpawnFakeRemotes { count: args.count }
    }
}

impl __sdk::InModule for SpawnFakeRemotesArgs {
    type Module = super::RemoteModule;
}

pub struct SpawnFakeRemotesCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `spawn_fake_remotes`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait spawn_fake_remotes {
    /// Request that the remote module invoke the reducer `spawn_fake_remotes` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_spawn_fake_remotes`] callbacks.
    fn spawn_fake_remotes(&self, count: u32) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `spawn_fake_remotes`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SpawnFakeRemotesCallbackId`] can be passed to [`Self::remove_on_spawn_fake_remotes`]
    /// to cancel the callback.
    fn on_spawn_fake_remotes(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u32) + Send + 'static,
    ) -> SpawnFakeRemotesCallbackId;
    /// Cancel a callback previously registered by [`Self::on_spawn_fake_remotes`],
    /// causing it not to run in the future.
    fn remove_on_spawn_fake_remotes(&self, callback: SpawnFakeRemotesCallbackId);
}

impl spawn_fake_remotes for super::RemoteReducers {
    fn spawn_fake_remotes(&self, count: u32) -> __sdk::Result<()> {
        self.imp
            .call_reducer("spawn_fake_remotes", SpawnFakeRemotesArgs { count })
    }
    fn on_spawn_fake_remotes(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u32) + Send + 'static,
    ) -> SpawnFakeRemotesCallbackId {
        SpawnFakeRemotesCallbackId(self.imp.on_reducer(
            "spawn_fake_remotes",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::SpawnFakeRemotes { count },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, count)
            }),
        ))
    }
    fn remove_on_spawn_fake_remotes(&self, callback: SpawnFakeRemotesCallbackId) {
        self.imp.remove_on_reducer("spawn_fake_remotes", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `spawn_fake_remotes`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_spawn_fake_remotes {
    /// Set the call-reducer flags for the reducer `spawn_fake_remotes` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn spawn_fake_remotes(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_spawn_fake_remotes for super::SetReducerFlags {
    fn spawn_fake_remotes(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("spawn_fake_remotes", flags);
    }
}
