// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::tick_timer_type::TickTimer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `tick_timer`.
///
/// Obtain a handle from the [`TickTimerTableAccess::tick_timer`] method on [`super::RemoteTables`],
/// like `ctx.db.tick_timer()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.tick_timer().on_insert(...)`.
pub struct TickTimerTableHandle<'ctx> {
    imp: __sdk::TableHandle<TickTimer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `tick_timer`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TickTimerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TickTimerTableHandle`], which mediates access to the table `tick_timer`.
    fn tick_timer(&self) -> TickTimerTableHandle<'_>;
}

impl TickTimerTableAccess for super::RemoteTables {
    fn tick_timer(&self) -> TickTimerTableHandle<'_> {
        TickTimerTableHandle {
            imp: self.imp.get_table::<TickTimer>("tick_timer"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TickTimerInsertCallbackId(__sdk::CallbackId);
pub struct TickTimerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TickTimerTableHandle<'ctx> {
    type Row = TickTimer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TickTimer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TickTimerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TickTimerInsertCallbackId {
        TickTimerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TickTimerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TickTimerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TickTimerDeleteCallbackId {
        TickTimerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TickTimerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TickTimer>("tick_timer");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}
pub struct TickTimerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TickTimerTableHandle<'ctx> {
    type UpdateCallbackId = TickTimerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TickTimerUpdateCallbackId {
        TickTimerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TickTimerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<TickTimer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TickTimer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `scheduled_id` unique index on the table `tick_timer`,
/// which allows point queries on the field of the same name
/// via the [`TickTimerScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.tick_timer().scheduled_id().find(...)`.
pub struct TickTimerScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TickTimer, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TickTimerTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `tick_timer`.
    pub fn scheduled_id(&self) -> TickTimerScheduledIdUnique<'ctx> {
        TickTimerScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TickTimerScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<TickTimer> {
        self.imp.find(col_val)
    }
}
