// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::collider_shape_type::ColliderShape;
use super::db_quat_type::DbQuat;
use super::db_vec_3_type::DbVec3;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct WorldStatic {
    pub id: u32,
    pub translation: DbVec3,
    pub rotation: DbQuat,
    pub scale: DbVec3,
    pub shape: ColliderShape,
}

impl __sdk::InModule for WorldStatic {
    type Module = super::RemoteModule;
}
