// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::collider_shape_type::ColliderShape;
use super::db_quat_type::DbQuat;
use super::db_vec_3_type::DbVec3;
use super::world_static_type::WorldStatic;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `world_static`.
///
/// Obtain a handle from the [`WorldStaticTableAccess::world_static`] method on [`super::RemoteTables`],
/// like `ctx.db.world_static()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.world_static().on_insert(...)`.
pub struct WorldStaticTableHandle<'ctx> {
    imp: __sdk::TableHandle<WorldStatic>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `world_static`.
///
/// Implemented for [`super::RemoteTables`].
pub trait WorldStaticTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`WorldStaticTableHandle`], which mediates access to the table `world_static`.
    fn world_static(&self) -> WorldStaticTableHandle<'_>;
}

impl WorldStaticTableAccess for super::RemoteTables {
    fn world_static(&self) -> WorldStaticTableHandle<'_> {
        WorldStaticTableHandle {
            imp: self.imp.get_table::<WorldStatic>("world_static"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct WorldStaticInsertCallbackId(__sdk::CallbackId);
pub struct WorldStaticDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for WorldStaticTableHandle<'ctx> {
    type Row = WorldStatic;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = WorldStatic> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = WorldStaticInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldStaticInsertCallbackId {
        WorldStaticInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WorldStaticInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = WorldStaticDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldStaticDeleteCallbackId {
        WorldStaticDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WorldStaticDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<WorldStatic>("world_static");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}
pub struct WorldStaticUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for WorldStaticTableHandle<'ctx> {
    type UpdateCallbackId = WorldStaticUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WorldStaticUpdateCallbackId {
        WorldStaticUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WorldStaticUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<WorldStatic>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<WorldStatic>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `world_static`,
/// which allows point queries on the field of the same name
/// via the [`WorldStaticIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.world_static().id().find(...)`.
pub struct WorldStaticIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<WorldStatic, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> WorldStaticTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `world_static`.
    pub fn id(&self) -> WorldStaticIdUnique<'ctx> {
        WorldStaticIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> WorldStaticIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<WorldStatic> {
        self.imp.find(col_val)
    }
}
